### ISSUE TITLE
Typo in strings.sh?

### ISSUE THREAD

**Issue by sealabcore** [meh/ruby-tesseract-ocr#28]
I get a compile error and the logs seem to have a misspelled filename:
# include <tesseract/strngs.h>

g++ -dynamic -bundle -fPIC    -o /var/folders/c4/m5y9xzwx7vz6bf9bc2cskfbw0000gn/T/.ffi-inline-501/1520ea0a1d2ef0361364717a891f35ab5f2a6c3f.dylib /var/folders/c4/m5y9xzwx7vz6bf9bc2cskfbw0000gn/T/.ffi-inline-501/1520ea0a1d2ef0361364717a891f35ab5f2a6c3f.cpp -ltesseract 2>>/var/folders/c4/m5y9xzwx7vz6bf9bc2cskfbw0000gn/T/.ffi-inline-501/1520ea0a1d2ef0361364717a891f35ab5f2a6c3f.log
/var/folders/c4/m5y9xzwx7vz6bf9bc2cskfbw0000gn/T/.ffi-inline-501/1520ea0a1d2ef0361364717a891f35ab5f2a6c3f.cpp:1:10: fatal error: 'tesseract/strngs.h' file not found
# include <tesseract/strngs.h>

```
     ^
```

1 error generated.

**Comment by jasonfb** [comment]
still here ? 

```
g++ -dynamic -bundle -fPIC  -L/opt/homebrew/opt/libffi/lib  -o /var/folders/_1/2js6pw0d6xl5x2d0wfmgs1kw0000gn/T/.ffi-inline-501/0cd77c7db3caadf526e7412ba9230427ea9d8f32.dylib /var/folders/_1/2js6pw0d6xl5x2d0wfmgs1kw0000gn/T/.ffi-inline-501/0cd77c7db3caadf526e7412ba9230427ea9d8f32.cpp -ltesseract 2>>/var/folders/_1/2js6pw0d6xl5x2d0wfmgs1kw0000gn/T/.ffi-inline-501/0cd77c7db3caadf526e7412ba9230427ea9d8f32.log
/var/folders/_1/2js6pw0d6xl5x2d0wfmgs1kw0000gn/T/.ffi-inline-501/0cd77c7db3caadf526e7412ba9230427ea9d8f32.cpp:1:10: fatal error: 'tesseract/strngs.h' file not found
#include <tesseract/strngs.h>
```
