### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kreba** [meh/ruby-tesseract-ocr#49]
Thanks for your work!

You state that you publish this under a "BSD one clause" license.
However, I cannot seem to find this license at a reliable source.
Please include a copy of the exact license text in a LICENSE file or a link to the definition you are referring to.

Thanks!

**Comment by meh** [comment]
The license text is in every source file.

**Comment by kreba** [comment]
@meh Thanks for your fast response. 
Since the license is of utmost importance, I simply did not check the source before I knew about the license. My mistake I guess. 
Still, it would seem to me that a small `(see source files)` or similar in the readme could be helpful to other potential users who actually care about the terms under which software is published.
For me this is fixed however, thanks again.
