### ISSUE TITLE
French support seems broken

### ISSUE THREAD

**Issue by pienkowskip** [meh/ruby-tesseract-ocr#54]
I've tried to run ocr on some French language images but there is strange error.

Debian package for French is tesseract-ocr-fra. So I installed it and run this code:
```
e = Tesseract::Engine.new {|e|
  e.language  = :fra
  e.blacklist = '|'
}
```

But I got such error:
```
Error opening data file /usr/share/tesseract-ocr/tessdata/fre.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'fre'
Tesseract couldn't load any languages!
```
So there is `fre` package required but I had written `:fra`. Ofc I tried `:fre` too but did not worked.

Here is my "tessdata" directory listing:
```
root@pablo-workstation:~# ls -l /usr/share/tesseract-ocr/tessdata/*.traineddata
-rw-r--r-- 1 root root 21876572 lut  2  2012 /usr/share/tesseract-ocr/tessdata/eng.traineddata
-rw-r--r-- 1 root root  2251826 wrz 26  2011 /usr/share/tesseract-ocr/tessdata/equ.traineddata
-rw-r--r-- 1 root root  3532163 lut  2  2012 /usr/share/tesseract-ocr/tessdata/fra.traineddata
-rw-r--r-- 1 root root 10562727 wrz 11  2009 /usr/share/tesseract-ocr/tessdata/osd.traineddata
-rw-r--r-- 1 root root 16977877 lut  2  2012 /usr/share/tesseract-ocr/tessdata/pol.traineddata
```
And there is `fra` package as you can see. `pol` and `eng` packages works well.

**Comment by meh** [comment]
Can you try master please? I just pushed something that should fix it.

**Comment by pienkowskip** [comment]
I've checked and now it is working properly. Thanks!

As I can see it supports both ISO 639-1 & 639-2. Good because I prefer ISO 639-1. I find it more common.

And now both `:fra` & `:fre` works ;)
