### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by manjiri** [meh/ruby-tesseract-ocr#7]
I added gem 'tesseract-ocr' to gemfile and ran a bundle install which was done. But on starting teh console, I get the following error:

/home/developer/............../gems/ffi-inline-0.0.4/lib/ffi/inline/compilers/gcc.rb:29:in `compile': compile error: see logs at /tmp/.ffi-inline-1001/79bfe26299a636ff2634d1772aa8982e9937a1ea.log (CompilationError)

my gcc versino is gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 
tesseract version is 3.02

I found a similar issue here which is closed but it doesnt work for me. Please help.

**Comment by MarcoLosito** [comment]
Please modify the readme to specify which tesseract versions works...that would have saved me a lot of time...

**Comment by kentarohorie** [comment]
@krajeshonline 
If you're using mac os, you can this.

```
brew install tesseract
```

or you should search 'install tesseract-ocr #{ your os }' on google.
